### PR TITLE
Add support for local system-specific version files

### LINKED ISSUE #37: Platform-agnostic .swift-version file
With the new Swift snapshot that we get from Xcode 8, it is now impossible (as far as I am aware, _please_ correct me if I'm wrong) to pin the proper Swift version on both OSX and Ubuntu. On OSX, the version is `3.0`. On Ubuntu, the correct version is `swift-3.0-preview-1`. 

What's the best approach/solution here?

### PR DESCRIPTION
**Pull request by Danappelxx**
Would resolve #37

### CODE REVIEW

**Comment by kylef** [comment]
I don't think this is the way to go forward. Since these previews offer breaking changes, specifying that Swift `3.0` is supported in your project's `.swift-version` file when it's not even out yet is not guaranteed it will work.

There will be no benefits of using swiftenv if you can't be certain that the locked version is actually the correct version that the project supports. swiftenv won't be able to accurately and reliably switch alpha/beta/preview versions of 3.0 in the future, since every 3.0 release regardless of them being the same version report as the same version.

**Comment by kylef** [comment]
This would also greatly complicate the `swiftenv local` behaviour when it may or may not need to override different files.

**Comment by Danappelxx** [comment]
That's fair, definitely not a fool-proof. This is a pretty big blocker for Zewo though so we'll be using this fork in the meantime. We'll also post the issue on bugs.swift.org so that the next preview will (hopefully) give the proper version of `swift-3.0-preview-2` instead of just `3.0`, which means that `3.0` will mean `3.0-preview-1` on OSX for a little while longer.

**Comment by kylef** [comment]
I think the best solution would be one of the following:

- Users manually add an alias for the correct version against an Xcode toolchain they've manually installed. That way, you can install multiple versions of Xcode and swiftenv can correctly manage the preview versions.

    ```shell
    $ ln -s /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/ ~/.swiftenv/versions/3.0-preview-1
    ````
- Swift starts versioning correctly.
- We find another way to determine the Swift version accurately from an Xcode install.

**Comment by Danappelxx** [comment]
Lets move this back over to #37

**Pull request closed without merging**
