### PR TITLE
Show progress bar for download

### PR DESCRIPTION
**Pull request by deepumukundan**
Show a progress bar while downloading the swift pkg file from Apple

### CODE REVIEW

**Comment by kylef** [comment]
Can we make the behaviour on Linux and OS X the same?

I'm also concerned this will mess up scripted output such as when this is used via Heroku and Travis CI. Could we perhaps retain the old behaviour unless the user has a tty terminal attached?

I think this could be done via:

```bash
if tty -s; then
  echo 'user has tty shell'
else
  echo 'user does not have a tty shell'
fi
```

**Comment by deepumukundan** [comment]
Good idea! I have changed the OS X implementation to switch between displaying progress or not based on terminal attached. I do not have a Linux instance right now to try this out on it and make the change for Linux. Can try that maybe after setting up a VM.

**Comment by kylef** [comment]
Okay, leave this with me. I'll apply change to Linux and test on both platforms soon.

Thanks for the PR.

**Comment by deepumukundan** [comment]
Thanks Kyle!

**Comment by kylef** [comment]
Thanks for the pull request, I've amended it slightly and merged it via 63180fa53253323746179b1664d5a2e9bf676e4b (left you as author so you get the credit).

I found that the `--progress-bar` output isn't great and instead enabled the full progress (removing -s).

**Comment by deepumukundan** [comment]
Gotcha. No problem. :+1:  It's hard to find out what happens in slower connections and the .pkg files are huge sometimes, so seeing any progress helps really

**Pull request closed without merging**
