### PR TITLE
A release version should not build from source

### PR DESCRIPTION
**Pull request by ikesyo**
Related to https://github.com/kylef/swiftenv/issues/56#issuecomment-247384953.

### CODE REVIEW

**Comment by kylef** [comment]
Thanks for the fix @ikesyo. To help me understand this fix, could you please explain how I can reproduce this issue?

**Comment by ikesyo** [comment]
https://github.com/kylef/swiftenv/issues/56#issuecomment-247384953 would be really the reproducible case: run `UBUNTU_VERSION=15.10 swiftenv install 3.0` on Ubuntu 16.04.

In that case `safe_get_platform` should return `ubuntu16.04` then swiftenv accesses `https://swiftenv-api.fuller.li/versions/3.0/binaries/ubuntu16.04` which returns 404, so the `build` flag is turned to `true`. After that, we fallback to [the check](https://github.com/ikesyo/swiftenv/blob/28e2d9554a7acdcaa6c97305fae3eb41a5704387/libexec/swiftenv-install#L265-L268), within the check `3.0` should turn the `build` flag to `false` since that is a binary release.

Another option for the `UBUNTU_VERSION` case would be taking into consideration `UBUNTU_VERSION` in `get_platform` and `safe_ get_platform`, right?

**Comment by kylef** [comment]
Right, so this PR is to make the auto detection of build flag to return `false` for `3.0` builds.

I don't believe this is the correct fix because it will cause every single version to have the `--no-build` by default. Defeating the purpose of the `auto` behaviour. This also means on platforms where there are no binary releases it will result in failing to build since it will use the binary releases.

**Comment by kylef** [comment]
Yes, I think we should make it so that `UBUNTU_VERSION` is respected in `safe_get_platform`. Or even make a new flag `PLATFORM` that replaces `UBUNTU_VERSION` completely. So it is not Ubuntu specific.

**Comment by kylef** [comment]
I'd also like to try and find a fallback for checking if ubuntu is installed without `lsb-release` to help solve some of these problems too. (Outside the scope of this PR I think).

**Comment by ikesyo** [comment]
> This also means on platforms where there are no binary releases it will result in failing to build since it will use the binary releases.

Thanks for the clarification. I'm closing this for now.

**Pull request closed without merging**
