### PR TITLE
Move and update swiftenv zsh completions

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by kylef** [comment]
What's the reason/justification for this change?

This change would break the completion completely and result in it no longer being included, check the logic at https://github.com/kylef/swiftenv/blob/master/libexec/swiftenv-init#L105-L111.

**Comment by keith** [comment]
Ah I hadn't seen that sourcing logic. I assumed it was requiring homebrew's completion directory and user configuration to function.

Before this swiftenv completion didn't work for me at all. Let me check this out again knowing that it should work without the updated homebrew formula.

**Comment by kylef** [comment]
Just checked your configuration in your dot files. You are using bash? https://github.com/keith/dotfiles/blob/b5736bddd02cd90ab9ae7da59c27e1e35099a183/langs/swift.bash#L5 because this PR mentions ZSH.

Either way, it's working for me on both bash, zsh and fish:

screen shot 2016-01-07 at 11 42 12

screen shot 2016-01-07 at 11 42 11

screen shot 2016-01-07 at 11 43 01

**Comment by keith** [comment]
That bash file is sourced from zsh. It's bash so it works with both.

**Comment by keith** [comment]
Ah. The problem is that sourcing of the zsh file doesn't work when installed via homebrew. Since `SWIFTENV_ROOT` is `~/.swiftenv` but the completions are in `$(brew --prefix swiftenv)/share/zsh/site-functions/swiftenv.zsh`

**Comment by keith** [comment]
I think because of homebrew's infrastructure for completions, shown in the homebrew PR, it makes sense to allow the user to set up the completions in this case. But that would require the rename for zsh which makes it more annoying for sure.

**Comment by kylef** [comment]
Okay, I'll have a play around with it via Homebrew installed. I think the logic to figure out the source path could just be adapted to figure out the source path relative to current source instead of using `SWIFTENV_ROOT`.

**Comment by keith** [comment]
This now throws an error for me:

```
% swiftenv<TAB>
_swiftenv:read:2: option valid only in functions called via compctl
Usage: swiftenv completions <command> <args...>
```

**Comment by keith** [comment]
Some of the updates from this PR could be applied to the zsh file, without the rename, to remove `compctl` which seems to be the "old way" of doing things http://zsh.sourceforge.net/Doc/Release/Completion-Using-compctl.html

**Pull request closed without merging**
